language: node_js
install: "npm install -g npm && npm install && ./node_modules/.bin/cake install"
# ensure our application is compiled before we run our tests
before_script: "./node_modules/.bin/cake compile"
script: "npm test"
node_js:
  - "0.10"
  - "0.8"
cache:
  directories:
    - node_modules
notifications:
  email: false
